### ISSUE TITLE
add link to examples

### ISSUE THREAD

**Issue by VladimirAlexiev** [validatingrdf/validatingrdf.github.io#11]
Do you maintain all source examples in github at https://github.com/labra/validatingRDFBookExamples/?
- Please add a link at http://book.validatingrdf.com
- Would be better to relocate them to https://github.com/validatingrdf, so the html book and the examples are in the same github location

**Comment by labra** [comment]
Indeed. good point. I will try to do that. Maybe defining another subdomain as: http://examples.validatingrdf.com which points to the github repository. 

I prefer not to relocate the repository because that's the url that appears in the printed book and I don't want to kill it.

**Comment by labra** [comment]
Added the link & updated
