### ISSUE TITLE
move book 1 level up (to domain)

### ISSUE THREAD

**Issue by VladimirAlexiev** [validatingrdf/validatingrdf.github.io#12]
http://validatingrdf.com shows a stock domain-seller page.
Wouldn't it be better to move the book there instead of the hostname http://book.validatingrdf.com?

**Comment by labra** [comment]
Yes. I need to add a landing page to http://validatingrdf.com. I prefer to keep the book subdomain, as I intend to add other subdomains later.

**Comment by labra** [comment]
Added a landing page
