### ISSUE TITLE
Table 5.10 and 5.11 are equal

### ISSUE THREAD

**Issue by mgskjaeveland** [validatingrdf/validatingrdf.github.io#16]
Looks like a copy-paste bug:
http://book.validatingrdf.com/bookHtml011.html#ch5.sec12.1
http://book.validatingrdf.com/bookHtml011.html#ch050NonValidatingProperties

**Comment by labra** [comment]
Thanks, the story is a bit more complicated than a copy-paste bug because the printed version of the book has those tables right, but there was indeed a bug there.

I will try to update the HTML version repairing that bug as soon as I find some time.
