### ISSUE TITLE
Add Apache Jena SHACL implementation to wiki

### ISSUE THREAD

**Issue by afs** [validatingrdf/validatingrdf.github.io#22]
Please add an entry for the Apache Jena SHACL implementation.
Thanks.

| name              | ver/date         | language | playground                                                                             | source/distribution                                                                                         | Uses/dependencies. Applied to                                                 | Contact                       |
|-------------------|------------------|----------|----------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------|-------------------------------|
||
| Apache Jena SHACL | 2019-09-25       | java     |                                                                                        | https://github.com/apache/jena/, maven: org.apache.jena:jena-shacl                                          | Apache Jena                                                                   | users@jena.apache.org         |

The same content in a file attached in case long lines cause problems:
[apache-jena-shacl.txt](https://github.com/validatingrdf/validatingrdf.github.io/files/4124407/apache-jena-shacl.txt)

**Comment by labra** [comment]
Thanks for the suggestion. I have just added it to the table. I am sorry for the delay, but it seems I missed the notification from this issue and didn't notice it until now.

By the way, I included Jena SHACL as another implementation in http://rdfshape.weso.es so when validating with SHACL, one can choose 3 different engines: SHaclEX, Jena SHACL and the Top Braid SHACL API.
